language: python
git:
  submodules: false
os: linux
install:
  - pip install .
  - pip install pytest-cov
before_script:
  - echo $RUN_CONFIG > bin/run_conf.cfg
script:
  - python -m pytest --cov-report=xml --cov=mb_modelbase tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)